remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/img/logo.png
show_downloads: true
title: Tepe
description: End-to-end token-gating
github:
  is_user_page: false
  is_project_page: true
  repository_url: https://github.com/TepeProject
  windows_url: https://github.com/TepeProject/tepe-app/releases/download/0.1.0/tepe.exe
  mac_url: https://github.com/TepeProject/tepe-app/releases/download/0.1.0/Tepe-0.1.0-arm64.dmg
google_analytics: G-0BMS4DTCG0
