remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
logo: /assets/img/logo.png
show_downloads: false
title: Tepe
description: End-to-end token-gating
github:
  is_project_page: true
  repository_url: https://github.com/TepeProject
